[project]
name = "inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiortc>=1.14.0",
    "fastapi[standard]>=0.119.0",
    "opencv-python>=4.12.0.88",
    "ultralytics>=8.3.213",
]
